import QtQuick

QtObject {

    ////////// ============== default theme ============== //////////
    // === Chair dynamic colors ===
    property color chair_vertical_line_Color: "steelblue"
    property color chair_top_cushion_color: "lightsteelblue"
    property color chair_horizontal_line_color: "steelblue"
    property color chair_joint_color: "darkblue"
    property color chair_right_button_color: "transparent"
    property color chair_right_button_border_color: "#4CAF50"
    property color chair_right_button_arrow_color: "#4CAF50"
    property color chair_left_button_color: "transparent"
    property color chair_left_button_border_color: "#2196F3"
    property color chair_left_button_arrow_color: "#2196F3"
    property color chair_angle_box_color: "#ffffff"
    property color chair_angle_box_border_color: "gray"
    property color chair_angle_text_color: "black"

    // === Fuel dynamic colors ===
    property color fuel_color: "greenyellow" // transparent
    property color fuel_model_7_color: "white"
    property color fuel_needle_color: "red" // red
    property color fuel_text_color: "white"

    // === Momrec dynamic colors ===
    property color momrec_gauge_circle_color: "black"
    property color momrec_gauge_circle_text_color: "red"

    // === Speedometer dynamic colors ===
    property color speedo_meter_color: "transparent"
    property color speedo_meter_model_13_color: "yellow"
    property color speedo_meter_needle_color: "red"
    property color speedo_meter_text_color: "black"

    // === Tachometer dynamic colors ===
    property color tacho_meter_rpm_color: "transparent"
    property color tacho_meter_rpm_model_13_color: "yellow"
    property color tacho_meter_needle_color: "red"

    // === Button and background colors ===
    property color right_button_color: "#4CAF50"
    property color left_button_color: "#2100FF"
    property color window_background_color: "#FFFFFF"

    // ===  function change theme ===
    property string current_theme: ""

    function apply_theme(current_theme) {
        ////////// ============== Arcane theme ============== //////////
        if (current_theme === "Arcane") {
            chair_vertical_line_Color = "steelblue"
            chair_top_cushion_color = "powderblue"
            chair_horizontal_line_color = "steelblue"
            chair_joint_color = "powderblue"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "springgreen"
            chair_right_button_arrow_color = "springgreen"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "aqua"
            chair_left_button_arrow_color = "aqua"
            chair_angle_box_color = "transparent"
            chair_angle_box_border_color = "gray"
            chair_angle_text_color = "aliceblue"
            fuel_color = "transparent"
            fuel_model_7_color = "springgreen"
            fuel_needle_color = "fuchsia"
            fuel_text_color = "aliceblue"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "deeppink"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "aqua"
            speedo_meter_needle_color = "fuchsia"
            speedo_meter_text_color = "aliceblue"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "aquamarine"
            tacho_meter_needle_color = "fuchsia"
            right_button_color = "aquamarine"
            left_button_color = "aquamarine"
            window_background_color = "black"
        } ////////// ============== Natural theme ============== //////////
        else if (current_theme === "Natural") {
            chair_vertical_line_Color = "darkslategray"
            chair_top_cushion_color = "lightseagreen"
            chair_horizontal_line_color = "darkslategray"
            chair_joint_color = "lightseagreen"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "cyan"
            chair_right_button_arrow_color = "darkblue"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "cyan"
            chair_left_button_arrow_color = "darkblue"
            chair_angle_box_color = "springgreen"
            chair_angle_box_border_color = "black"
            chair_angle_text_color = "maroon"
            fuel_color = "transparent"
            fuel_model_7_color = "red"
            fuel_needle_color = "green"
            fuel_text_color = "black"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "black"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "red"
            speedo_meter_needle_color = "green"
            speedo_meter_text_color = "black"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "red"
            tacho_meter_needle_color = "green"
            right_button_color = "yellow"
            left_button_color = "yellow"
            window_background_color = "mediumaquamarine"
        } ////////// ============== Kali theme ============== //////////
        else if (current_theme === "Kali") {
            chair_vertical_line_Color = "steelblue"
            chair_top_cushion_color = "lightsteelblue"
            chair_horizontal_line_color = "steelblue"
            chair_joint_color = "darkblue"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "#4CAF50"
            chair_right_button_arrow_color = "#4CAF50"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "#2196F3"
            chair_left_button_arrow_color = "#2196F3"
            chair_angle_box_color = "#ffffff"
            chair_angle_box_border_color = "gray"
            chair_angle_text_color = "black"
            fuel_color = "transparent"
            fuel_model_7_color = "white"
            fuel_needle_color = "gray"
            fuel_text_color = "white"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "red"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "yellow"
            speedo_meter_needle_color = "red"
            speedo_meter_text_color = "black"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "yellow"
            tacho_meter_needle_color = "red"
            right_button_color = "greenyellow"
            left_button_color = "greenyellow"
            window_background_color = "lightgreen"
        } ////////// ============== Galaxy theme ============== //////////
        else if (current_theme === "Galaxy") {
            chair_vertical_line_Color = "steelblue"
            chair_top_cushion_color = "lightsteelblue"
            chair_horizontal_line_color = "steelblue"
            chair_joint_color = "darkblue"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "#4CAF50"
            chair_right_button_arrow_color = "#4CAF50"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "#2196F3"
            chair_left_button_arrow_color = "#2196F3"
            chair_angle_box_color = "#ffffff"
            chair_angle_box_border_color = "gray"
            chair_angle_text_color = "black"
            fuel_color = "transparent"
            fuel_model_7_color = "white"
            fuel_needle_color = "gray"
            fuel_text_color = "white"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "red"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "yellow"
            speedo_meter_needle_color = "red"
            speedo_meter_text_color = "black"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "yellow"
            tacho_meter_needle_color = "red"
            right_button_color = "greenyellow"
            left_button_color = "greenyellow"
            window_background_color = "#FFFFFF"
        } ////////// ============== Giza theme ============== //////////
        else if (current_theme === "Giza") {
            chair_vertical_line_Color = "steelblue"
            chair_top_cushion_color = "lightsteelblue"
            chair_horizontal_line_color = "steelblue"
            chair_joint_color = "darkblue"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "#4CAF50"
            chair_right_button_arrow_color = "#4CAF50"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "#2196F3"
            chair_left_button_arrow_color = "#2196F3"
            chair_angle_box_color = "#ffffff"
            chair_angle_box_border_color = "gray"
            chair_angle_text_color = "black"
            fuel_color = "transparent"
            fuel_model_7_color = "white"
            fuel_needle_color = "gray"
            fuel_text_color = "white"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "red"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "yellow"
            speedo_meter_needle_color = "red"
            speedo_meter_text_color = "black"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "yellow"
            tacho_meter_needle_color = "red"
            right_button_color = "greenyellow"
            left_button_color = "greenyellow"
            window_background_color = "#FFFFFF"
        } ////////// ============== Tanta theme ============== //////////
        else if (current_theme === "Tanta") {
            chair_vertical_line_Color = "steelblue"
            chair_top_cushion_color = "lightsteelblue"
            chair_horizontal_line_color = "steelblue"
            chair_joint_color = "darkblue"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "#4CAF50"
            chair_right_button_arrow_color = "#4CAF50"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "#2196F3"
            chair_left_button_arrow_color = "#2196F3"
            chair_angle_box_color = "#ffffff"
            chair_angle_box_border_color = "gray"
            chair_angle_text_color = "black"
            fuel_color = "transparent"
            fuel_model_7_color = "white"
            fuel_needle_color = "gray"
            fuel_text_color = "white"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "red"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "yellow"
            speedo_meter_needle_color = "red"
            speedo_meter_text_color = "black"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "yellow"
            tacho_meter_needle_color = "red"
            right_button_color = "greenyellow"
            left_button_color = "greenyellow"
            window_background_color = "#FFFFFF"
        } ////////// ============== Linux theme ============== //////////
        else if (current_theme === "Linux") {
            chair_vertical_line_Color = "steelblue"
            chair_top_cushion_color = "lightsteelblue"
            chair_horizontal_line_color = "steelblue"
            chair_joint_color = "darkblue"
            chair_right_button_color = "transparent"
            chair_right_button_border_color = "#4CAF50"
            chair_right_button_arrow_color = "#4CAF50"
            chair_left_button_color = "transparent"
            chair_left_button_border_color = "#2196F3"
            chair_left_button_arrow_color = "#2196F3"
            chair_angle_box_color = "#ffffff"
            chair_angle_box_border_color = "gray"
            chair_angle_text_color = "black"
            fuel_color = "transparent"
            fuel_model_7_color = "white"
            fuel_needle_color = "gray"
            fuel_text_color = "white"
            momrec_gauge_circle_color = "black"
            momrec_gauge_circle_text_color = "red"
            speedo_meter_color = "transparent"
            speedo_meter_model_13_color = "yellow"
            speedo_meter_needle_color = "red"
            speedo_meter_text_color = "black"
            tacho_meter_rpm_color = "transparent"
            tacho_meter_rpm_model_13_color = "yellow"
            tacho_meter_needle_color = "red"
            right_button_color = "greenyellow"
            left_button_color = "greenyellow"
            window_background_color = "#FFFFFF"
        }
    }
}
